### ISSUE TITLE
I see what you did there...

### ISSUE THREAD

**Issue by uschtwill** [bvis/docker-prometheus-swarm#12]
... and I like what I see! :)

Just saw your [Docker Swarm dashboard](https://grafana.com/dashboards/609) and thought it looked familiar. Thanks for referencing my work - I love what you did with it!

I thought about making [the suite](https://github.com/uschtwill/docker_monitoring_logging_alerting) swarm-aware for a long time but haven't got around doing it. Maybe we can team up? What do you think?

EDIT: And sorry for putting this as an issue, I just thought it was the easiest way to reach out to you. :)

**Comment by bvis** [comment]
Hi, @uschtwill

Of course we could team up. I'm @basi in Twitter, just contact me when you want.
