### ISSUE TITLE
Docker exporter not loading.

### ISSUE THREAD

**Issue by bweston92** [bvis/docker-prometheus-swarm#14]
Docker exporter container is running but cannot access the port 4999 it just times out which also means there is an alert running by default.

**Comment by bvis** [comment]
Hi,

For the docker-exporter service you need to activate the metrics API in your docker daemons.
Here you have 2 options:

a. Activate it. You have info about the process here: https://medium.com/@basi/docker-swarm-metrics-in-prometheus-e02a6a5745a
b. Remove the docker-exporter service from your compose file. It shouldn't produce any alert as Prometheus simply assumes there aren't tasks to discover

If these are not valid solutions for your use case, just contact me again.
