### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by timchenxiaoyu** [bvis/docker-prometheus-swarm#2]
my cadvisor container eth0 has two IP ,so network cann't connect

74: eth0@if75: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 02:42:0a:00:00:05 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.5/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.0.0.2/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:fe00:5/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by bvis** [comment]
Could you be more concrete about your error? Do you mean that prometheus can't connect to cadvisor?

**Comment by bvis** [comment]
Any news about your issue? If you don't say anything about it in the next days I'll assume that this is not a problem for you anymore.

**Comment by timchenxiaoyu** [comment]
sorry,I am later to response, No Problem now
