### ISSUE TITLE
Missing datasources ?

### ISSUE THREAD

**Issue by machzqcq** [bvis/docker-prometheus-swarm#3]
Hi,
I was able to up the stack using docker stack command and it came up fine on the swarm as attached. However, when I try to import the .json file for the graphana dashboard, it asks for the data sources (elastic search, prometheus and alerts) and I cannot click "Import", because it expects all fields to be filled in. I tried combinations 
- Setting up prometheus endpoint as `http://prometheus:9090` , `http://localhost:9090` , which complained about bad gateway
- Also tried for elasticsearch datasource using `http://localhost:9200`

By the time I reached this point with errors in both prometheus and elastic search, I was doubtful if I am going the right direction. 

My expectation was that once the stack is up and running, it has everything that it needs to see the dashboard and evaluate further - Is that not the case ? There is more to set up than just standing up the stack using `docker stack` ?

![image](https://cloud.githubusercontent.com/assets/6425159/24580038/191625f0-16cf-11e7-82e7-ef5dc2d1a152.png)

![image](https://cloud.githubusercontent.com/assets/6425159/24580034/0befb030-16cf-11e7-929c-c121039d377d.png)

**Comment by bvis** [comment]
Hi, I've updated the stack defaults to avoid the problem you found and I've added another stack that can be used as a sample to test the logging features and the integration with the monitoring stack.

I hope you find it useful.
