### ISSUE TITLE
network conflicts

### ISSUE THREAD

**Issue by dcrystalj** [bvis/docker-prometheus-swarm#7]
When I deploy stack in swarm mode i get this error for prometheus for example:

`$docker service ps monitoring_prometheus  --no-trunc`
```
monitoring_prometheus.1  basi/prometheus-swarm:v0.4.3@sha256:e39a... swarm-01 
Shutdown       Failed 5 seconds ago             
"starting container failed: subnet sandbox join failed for "10.0.2.0/24": overlay subnet 10.0.2.0/24 has conflicts in the host while running in host mode" 
```
is it problem because stack deploy creates network `monitoring_monitoring` ? 
I managed to start services by creating network `docker network create --driver overlay monitoring`.
But then I still have some network problems to access services using reverse proxy (i can acces only services on one node)

**Comment by bvis** [comment]
What's the version of docker you are using?
Does your swarm cluster have something specific in configuration?
How have you deployed the stack?

On theory swarm manages the network addresses automatically and avoids collisions, unless you have defined some network ranges manually, in that case a collision is possible.

**Comment by dcrystalj** [comment]
im using everything latest.
This was so weird. Solution was to restart docker daemon on all nodes simultaniously.
